    development:
      adapter: postgresql
      database: workshop_email_app_development
      pool: 5
      username: robertwilliams
      password: secret
      host: localhost
      port: 5432

    test:
      adapter: postgresql
      database: workshop_email_app_test
      pool: 5
      username: robertwilliams
      password: secret
      host: localhost
      port: 5432

    production:
      adapter: postgresql
      database: workshop_email_app_production
      pool: 5
      username: robertwilliams
      password: secret
      host: localhost
      port: 5432