    development:
      adapter: postgresql
      database: workshop_email_app_development
      username: robert
      password:

    test:
      adapter: postgresql
      database: workshop_email_app_test
      username: robert
      password:

    production:
      adapter: postgresql
      database: workshop_email_app_production
      username: robert
      password: